export const BASEURL = "https://blog-server-two-phi.vercel.app/api";
// export const BASEURL = "http://localhost:4000/api";
export const REGISTER = "auth/register"; 
export const LOGIN = "auth/login";
export const USERS = "users";
export const POSTS = "posts";
export const COUNT = "count";
export const LIKE = "like";
export const COMMENTS = "comments";
